### PR TITLE
doing my part

### PR DESCRIPTION
**Pull request by duretti**
`thoughtstradamus` is such a better name than `Thoughtleaders`

this also buys me time until I come up with some fire thoughts to lead

### CODE REVIEW

**Comment by duretti** [comment]
oh weird! why didn't this get caught as apart of #2 

weiiiiiird

**Comment by Randommood** [comment]
yeah, repo's been pretty busy ... if it keeps up I may have to ping @jfrazelle to teach me how to be a better maintainerati ;)

**Comment by Randommood** [comment]
also, I'd love the Duretti thought leader terms of 2017... slayops?

**Comment by duretti** [comment]
lolololol i have no good terms, but i will try and think of some

**Comment by OleMchls** [comment]
Because my 2nd commit 63694e9c4d768b1ece306bcf5c7d4fa60ed77af6 really fucked 💩 up 😢

**Pull request closed without merging**
